/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import handModel from'./hand-model.glb'

export default function HandModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(handModel)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="node_MeshObject-1005584384-PolyPaper23"
        geometry={nodes['node_MeshObject-1005584384-PolyPaper23'].geometry}
        material={materials.BlocksPaper}
        // position={[-1.7, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(handModel)
