/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import MouseGlb from './mouse.glb'

export default function Mouse(props) {
    const group = useRef()
    const {nodes, materials} = useGLTF(MouseGlb)
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group>
                    <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material__2}/>
                    {/*<mesh geometry={nodes.Mesh_0001.geometry} material={materials.Material} />*/}
                    <mesh geometry={nodes.Mesh_0001.geometry}>
                        <meshStandardMaterial attach='material' color={"#a0e734"}/>
                    </mesh>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/mouse.glb')
