/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Blender(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/blender.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve009.geometry}
        material={materials['SVGMat.010']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve008.geometry}
        material={materials['SVGMat.009']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve007.geometry}
        material={materials['SVGMat.008']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve006.geometry}
        material={materials['SVGMat.007']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials['SVGMat.006']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve004.geometry}
        material={materials['SVGMat.005']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials['SVGMat.004']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials['SVGMat.003']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials['SVGMat.002']}
        position={[-7.73, 12.18, 0]}
        rotation={[1.53, 0, 0]}
        scale={88.16}
      />
    </group>
  )
}

useGLTF.preload('/blender.glb')
